# Generated by Django 5.2.4 on 2025-11-18 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('change_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(db_column='design_id', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='designs.design')),
            ],
            options={
                'db_table': 'design_change_log',
                'indexes': [models.Index(fields=['design', '-created_at'], name='design_chan_design__71a6e0_idx'), models.Index(fields=['user_id'], name='design_chan_user_id_2ce8c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesignCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20)),
                ('invited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(db_column='design_id', on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='designs.design')),
            ],
            options={
                'db_table': 'design_collaborators',
                'indexes': [models.Index(fields=['design'], name='design_coll_design__bbb1bd_idx'), models.Index(fields=['user_id'], name='design_coll_user_id_cbd567_idx')],
                'unique_together': {('design', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='DesignComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField()),
                ('x', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(db_column='design_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='designs.design')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.designcomment')),
            ],
            options={
                'db_table': 'design_comments',
                'indexes': [models.Index(fields=['design', '-created_at'], name='design_comm_design__6b01fc_idx'), models.Index(fields=['object_id'], name='design_comm_object__802492_idx'), models.Index(fields=['parent'], name='design_comm_parent__8dcf08_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('created_by', models.CharField(max_length=255)),
                ('snapshot', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(db_column='design_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designs.design')),
            ],
            options={
                'db_table': 'design_versions',
                'indexes': [models.Index(fields=['design', '-version_number'], name='design_vers_design__b89f7f_idx')],
                'unique_together': {('design', 'version_number')},
            },
        ),
    ]
