# Generated by Django 5.2.4 on 2025-11-18 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='in', max_length=10)),
                ('dpi', models.IntegerField(default=300)),
                ('bleed', models.DecimalField(decimal_places=2, default=0.125, max_digits=10)),
                ('color_mode', models.CharField(default='rgb', max_length=10)),
                ('last_edited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'designs',
                'indexes': [models.Index(fields=['user_id'], name='designs_user_id_5fdfbf_idx'), models.Index(fields=['updated_at'], name='designs_updated_650c86_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesignObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rotation', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('opacity', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('z_index', models.IntegerField()),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_objects', to='designs.design')),
            ],
            options={
                'db_table': 'design_objects',
                'indexes': [models.Index(fields=['design', 'z_index'], name='design_obje_design__989403_idx')],
            },
        ),
    ]
