# Generated by Django 5.2.4 on 2025-11-18 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG'), ('svg', 'SVG')], max_length=10)),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra', 'Ultra')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('result_url', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('design', models.ForeignKey(db_column='design_id', on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='designs.design')),
            ],
            options={
                'db_table': 'export_jobs',
                'indexes': [models.Index(fields=['design'], name='export_jobs_design__20957a_idx'), models.Index(fields=['user_id', '-created_at'], name='export_jobs_user_id_e522fa_idx'), models.Index(fields=['status', '-created_at'], name='export_jobs_status_469dfe_idx')],
            },
        ),
    ]
