# Generated by Django 5.2.4 on 2025-11-18 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('preview_url', models.TextField(blank=True, null=True)),
                ('design_data', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('downloads', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templates',
                'indexes': [models.Index(fields=['category'], name='templates_categor_206a35_idx'), models.Index(fields=['industry'], name='templates_industr_96de46_idx'), models.Index(fields=['-downloads', '-rating'], name='templates_downloa_35abcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateAnalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('use', 'Use'), ('download', 'Download')], max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='design_templates.template')),
            ],
            options={
                'db_table': 'template_analytics',
                'indexes': [models.Index(fields=['template', '-created_at'], name='template_an_templat_e5b12d_idx'), models.Index(fields=['event_type', '-created_at'], name='template_an_event_t_4143d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='design_templates.template')),
            ],
            options={
                'db_table': 'template_favorites',
                'indexes': [models.Index(fields=['user_id'], name='template_fa_user_id_fd67de_idx')],
                'unique_together': {('template', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='TemplateShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='design_templates.template')),
            ],
            options={
                'db_table': 'template_shares',
                'indexes': [models.Index(fields=['share_token'], name='template_sh_share_t_26edf4_idx'), models.Index(fields=['template'], name='template_sh_templat_75be86_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('design_data', models.JSONField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='design_templates.template')),
            ],
            options={
                'db_table': 'template_versions',
                'indexes': [models.Index(fields=['template', '-version_number'], name='template_ve_templat_02ce95_idx')],
                'unique_together': {('template', 'version_number')},
            },
        ),
    ]
